#!/bin/bash
# =====================================================================
#  build-installer.sh — build install.sh from LIVE panel files
#  Run on the server:  sudo bash build-installer.sh
#  Output: /root/install.sh  → paste into GitHub (Panel-L2TP/install.sh)
# =====================================================================
set -euo pipefail
PANEL_DIR="/opt/l2tp-panel"
OUT="${1:-/root/install.sh}"

for f in panel.py sync_users.py iface_down.py \
         templates/base.html templates/login.html templates/index.html \
         templates/user.html templates/restarting.html templates/updating.html; do
  [ -f "${PANEL_DIR}/${f}" ] || { echo "[X] Missing: ${PANEL_DIR}/${f}"; exit 1; }
done

echo "[*] Generating ${OUT} from live panel files..."

# ==================== PART 1: static installer ====================
cat > "$OUT" <<'PART1'
#!/bin/bash
# =====================================================================
#   3OUTHBOY PANEL — L2TP/IPSec VPN + Web Management Panel  v1.0.1
#   Auto-generated by build-installer.sh (server files = source of truth)
#   Ubuntu 20.04 / 22.04 / 24.04
#   Interactive:  sudo bash install.sh
#   Unattended:   sudo bash install.sh --user admin --pass X --port 8080 --psk Y
# =====================================================================
set -euo pipefail

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info(){ echo -e "${CYAN}[*]${NC} $1"; }
ok(){   echo -e "${GREEN}[OK]${NC} $1"; }
warn(){ echo -e "${YELLOW}[!]${NC} $1"; }
die(){  echo -e "${RED}[X]${NC} $1"; exit 1; }

[ "$EUID" -eq 0 ] || die "This script must be run with sudo."

PANEL_DIR="/opt/l2tp-panel"
POOL_NET="192.168.43.0/24"
POOL_START="192.168.43.10"; POOL_END="192.168.43.250"; L2TP_LOCAL_IP="192.168.43.1"
XAUTH_NET="192.168.44.0/24"

rand_str(){
  local len=${1:-20} out=""
  while [ "${#out}" -lt "$len" ]; do
    out+="$(head -c 64 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${out:0:$len}"
}
sanitize(){ printf '%s' "$1" | LC_ALL=C tr -d '\042\047\134\052\072\073\040\011\012\043'; }

ADMIN_USER="admin"; ADMIN_PASS="$(rand_str 12)"; PANEL_PORT="8080"
PSK="$(rand_str 20)"; ADMIN_IP=""; SET_TZ="y"; ENABLE_UFW="y"
while [ $# -gt 0 ]; do
  case "$1" in
    --user)     ADMIN_USER="$2"; shift 2 ;;
    --pass)     ADMIN_PASS="$2"; shift 2 ;;
    --port)     PANEL_PORT="$2"; shift 2 ;;
    --psk)      PSK="$2"; shift 2 ;;
    --admin-ip) ADMIN_IP="$2"; shift 2 ;;
    --tz)       SET_TZ="$2"; shift 2 ;;
    --no-ufw)   ENABLE_UFW="n"; shift ;;
    *) shift ;;
  esac
done

if [ -t 0 ]; then
  echo -e "${CYAN}============ 3OUTHBOY PANEL Installer ============${NC}"
  read -rp "Panel admin username [${ADMIN_USER}]: " v; ADMIN_USER="${v:-$ADMIN_USER}"
  read -rp "Panel admin password [${ADMIN_PASS}]: " v; ADMIN_PASS="${v:-$ADMIN_PASS}"
  read -rp "Panel port (your choice) [${PANEL_PORT}]: " v; PANEL_PORT="${v:-$PANEL_PORT}"
  read -rp "IPSec pre-shared key (PSK) [${PSK}]: " v; PSK="${v:-$PSK}"
  read -rp "Admin IP allowed to open panel (empty = no restriction): " v; ADMIN_IP="${v:-$ADMIN_IP}"
  read -rp "Set server timezone to Asia/Tehran? [Y/n]: " v; SET_TZ="${v:-y}"
  read -rp "Enable UFW firewall? [Y/n]: " v; ENABLE_UFW="${v:-y}"
fi

ADMIN_USER="$(sanitize "$ADMIN_USER" | tr -cd 'A-Za-z0-9_.-')"
ADMIN_PASS="$(sanitize "$ADMIN_PASS")"; PSK="$(sanitize "$PSK")"
ADMIN_USER="${ADMIN_USER:-admin}"; ADMIN_PASS="${ADMIN_PASS:-$(rand_str 12)}"; PSK="${PSK:-$(rand_str 20)}"
[[ "$PANEL_PORT" =~ ^[1-9][0-9]{1,4}$ ]] || PANEL_PORT="8080"
if [ -n "$ADMIN_IP" ] && ! [[ "$ADMIN_IP" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?$ ]]; then
  warn "Invalid admin IP; panel will not be restricted."; ADMIN_IP=""
fi

# ----------------------------- Packages ------------------------------
info "Installing packages (this may take a few minutes)..."
export DEBIAN_FRONTEND=noninteractive
systemctl disable --now strongswan-starter strongswan-swanctl >/dev/null 2>&1 || true
apt-get remove -y strongswan-starter strongswan-swanctl libreswan >/dev/null 2>&1 || true
apt-get update -y -qq
apt-get install -y -qq xl2tpd strongswan strongswan-starter libcharon-extra-plugins \
  libstrongswan-extra-plugins ppp python3 python3-flask gunicorn ufw iptables curl >/dev/null
ok "Packages installed."

[ "${SET_TZ,,}" != "n" ] && timedatectl set-timezone Asia/Tehran >/dev/null 2>&1 && ok "Timezone: Asia/Tehran" || true

DEF_IF="$(ip -4 route show default 2>/dev/null | awk '{print $5; exit}')"
[ -n "$DEF_IF" ] || die "Could not find the default network interface."
SERVER_IP="$(ip -4 addr show dev "$DEF_IF" | grep -oP 'inet\s+\K[\d.]+' | head -1 || true)"
[ -n "$SERVER_IP" ] || SERVER_IP="$(hostname -I | awk '{print $1}')"

info "Detecting public IPv4 address..."
PUB_IP="$(curl -4 -s --max-time 6 https://api.ipify.org || true)"
[ -n "$PUB_IP" ] || PUB_IP="$(curl -4 -s --max-time 6 http://ipv4.icanhazip.com || true)"
[ -n "$PUB_IP" ] || PUB_IP="$(curl -4 -s --max-time 6 http://checkip.amazonaws.com || true)"
if [[ "$PUB_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  ok "Public IPv4: ${PUB_IP}"
else
  PUB_IP="$SERVER_IP"; warn "Could not detect public IPv4; using ${PUB_IP}."
fi
grep -q '^precedence ::ffff:0:0/96  100' /etc/gai.conf 2>/dev/null || \
  echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf

TS="$(date +%Y%m%d%H%M%S)"
for f in /etc/ipsec.conf /etc/ipsec.secrets /etc/xl2tpd/xl2tpd.conf \
         /etc/ppp/options.xl2tpd /etc/ppp/chap-secrets; do
  [ -f "$f" ] && cp -a "$f" "${f}.bak-${TS}"
done

# ----------------------------- IPSec ------------------------------
info "Configuring IPSec (strongSwan)..."
LEFTID=""; [[ "$PUB_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && LEFTID="    leftid=${PUB_IP}"

cat > /etc/ipsec.conf <<IPSECEOF
# 3OUTHBOY PANEL (strongSwan)
config setup
    uniqueids=no

conn shared
    keyexchange=ikev1
    left=%defaultroute
 ${LEFTID}
    right=%any
    forceencaps=yes
    authby=psk
    pfs=no
    rekey=no
    dpddelay=30
    dpdaction=clear
    ikelifetime=24h
    lifetime=24h
    ike=aes256-sha2_256-modp2048,aes128-sha2_256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048,aes256-sha2_256-curve25519,aes128-sha2_256-curve25519,aes256-sha1-curve25519,aes128-sha1-curve25519,aes256-sha2_256-ecp256,aes128-sha2_256-ecp256,aes256-sha2_256-modp1024,aes128-sha2_256-modp1024,aes256-sha1-modp1024,aes128-sha1-modp1024
    esp=aes256-sha2_256,aes128-sha2_256,aes256-sha2_512,aes256-sha1,aes128-sha1,aes128gcm16,aes256gcm16

conn l2tp-psk
    also=shared
    auto=add
    leftprotoport=17/1701
    rightprotoport=17/%any
    type=transport

conn xauth-psk
    also=shared
    auto=add
    leftsubnet=0.0.0.0/0
    rightaddresspool=192.168.44.10-192.168.44.250
    modecfgdns="8.8.8.8 8.8.4.4"
    xauth=server
    modeconfig=push
    cisco_unity=yes
IPSECEOF

printf '%%any %%any : PSK "%s"\n' "$PSK" > /etc/ipsec.secrets
chmod 600 /etc/ipsec.secrets
touch /etc/ipsec.d/passwd && chmod 600 /etc/ipsec.d/passwd

# ----------------------------- xl2tpd + PPP --------------------------
info "Configuring xl2tpd and PPP..."
cat > /etc/xl2tpd/xl2tpd.conf <<XL2TPDEOF
[global]
port = 1701

[lns default]
ip range = ${POOL_START}-${POOL_END}
local ip = ${L2TP_LOCAL_IP}
require chap = yes
refuse pap = yes
require authentication = yes
name = l2tpd
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
XL2TPDEOF

cat > /etc/ppp/options.xl2tpd <<'PPPOPT'
name l2tpd
ipcp-accept-local
ipcp-accept-remote
ms-dns 8.8.8.8
ms-dns 1.1.1.1
noccp
auth
crtscts
idle 1800
mtu 1410
mru 1410
lock
connect-delay 5000
lcp-echo-interval 30
lcp-echo-failure 5
PPPOPT

cat > /etc/ppp/ip-up.d/90l2tp-panel <<'IPUPEOF'
#!/bin/sh
SDIR=/run/l2tp-sessions
PDIR=/run/l2tp-peerip
IDIR=/run/l2tp-ifaces
DMAP=/etc/ppp/dns-map
[ -n "$PEERNAME" ] || exit 0
mkdir -p "$SDIR" "$PDIR" "$IDIR" 2>/dev/null || exit 0
P=$PPID; N=0
while [ -n "$P" ] && [ "$P" != "1" ] && [ "$P" != "0" ] && [ "$N" -lt 6 ]; do
    C=$(ps -o comm= -p "$P" 2>/dev/null)
    case "$C" in
        pppd*) echo "$P" > "$SDIR/$PEERNAME"; break ;;
    esac
    P=$(ps -o ppid= -p "$P" 2>/dev/null | tr -d ' '); N=$((N+1))
done
[ -n "$5" ] && echo "$5" > "$PDIR/$PEERNAME"
[ -n "$1" ] && printf '%s 0\n' "$PEERNAME" > "$IDIR/$1"
if [ -s "$DMAP/$PEERNAME" ] && [ -n "$5" ]; then
    DNS1=$(awk '{print $1}' "$DMAP/$PEERNAME" 2>/dev/null)
    if [ -n "$DNS1" ]; then
        for PROTO in udp tcp; do
            /sbin/iptables -t nat -C L2TP_DNS -s "$5" -p $PROTO --dport 53 -j DNAT --to-destination "$DNS1" 2>/dev/null || \
            /sbin/iptables -t nat -A L2TP_DNS -s "$5" -p $PROTO --dport 53 -j DNAT --to-destination "$DNS1" 2>/dev/null
        done
    fi
fi
exit 0
IPUPEOF
chmod 755 /etc/ppp/ip-up.d/90l2tp-panel

cat > /etc/ppp/ip-down.d/90l2tp-panel <<'IPDOWNEOF'
#!/bin/sh
SDIR=/run/l2tp-sessions
PDIR=/run/l2tp-peerip
IDIR=/run/l2tp-ifaces
DMAP=/etc/ppp/dns-map
if [ -n "$PEERNAME" ]; then
    if [ -s "$DMAP/$PEERNAME" ] && [ -n "$5" ]; then
        DNS1=$(awk '{print $1}' "$DMAP/$PEERNAME" 2>/dev/null)
        if [ -n "$DNS1" ]; then
            for PROTO in udp tcp; do
                /sbin/iptables -t nat -D L2TP_DNS -s "$5" -p $PROTO --dport 53 -j DNAT --to-destination "$DNS1" 2>/dev/null
            done
        done
    fi
    rm -f "$SDIR/$PEERNAME" "$PDIR/$PEERNAME" 2>/dev/null
fi
/usr/bin/python3 /opt/l2tp-panel/iface_down.py "$1" >/dev/null 2>&1
rm -f "$IDIR/$1" 2>/dev/null
exit 0
IPDOWNEOF
chmod 755 /etc/ppp/ip-down.d/90l2tp-panel

mkdir -p /run/l2tp-sessions /run/l2tp-ifaces /run/l2tp-peerip /etc/ppp/dns-map
chmod 700 /run/l2tp-sessions /run/l2tp-ifaces /run/l2tp-peerip /etc/ppp/dns-map

# ----------------------------- Network -------------------------------
info "Enabling IP forwarding and NAT..."
sed -i '/^#\?net.ipv4.ip_forward/d' /etc/sysctl.conf
echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=1 >/dev/null

cat > /usr/local/sbin/l2tp-nat.sh <<NATEOF
#!/bin/sh
IF="${DEF_IF}"
add(){ /sbin/iptables -t nat -C POSTROUTING -s "\$1" -o "\$IF" -j MASQUERADE 2>/dev/null || /sbin/iptables -t nat -A POSTROUTING -s "\$1" -o "\$IF" -j MASQUERADE; }
del(){ /sbin/iptables -t nat -D POSTROUTING -s "\$1" -o "\$IF" -j MASQUERADE 2>/dev/null || true; }
chain(){
  /sbin/iptables -t nat -N L2TP_DNS 2>/dev/null || true
  /sbin/iptables -t nat -C PREROUTING -j L2TP_DNS 2>/dev/null || /sbin/iptables -t nat -A PREROUTING -j L2TP_DNS
}
mss(){ /sbin/iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || /sbin/iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu; }
case "\$1" in
  start) add ${POOL_NET}; add ${XAUTH_NET}; chain; mss ;;
  stop)  del ${POOL_NET}; del ${XAUTH_NET}; /sbin/iptables -t nat -F L2TP_DNS 2>/dev/null || true ;;
esac
NATEOF
chmod 755 /usr/local/sbin/l2tp-nat.sh

cat > /etc/systemd/system/l2tp-nat.service <<'SVCEOF'
[Unit]
Description=3OUTHBOY PANEL - NAT for VPN clients
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/l2tp-nat.sh start
ExecStop=/usr/local/sbin/l2tp-nat.sh stop

[Install]
WantedBy=multi-user.target
SVCEOF

# ----------------------------- Panel files ---------------------------
info "Installing panel..."
mkdir -p "${PANEL_DIR}/templates"

cat > "${PANEL_DIR}/config.json" <<CONFEOF
{
  "admin_user": "${ADMIN_USER}",
  "admin_pass": "${ADMIN_PASS}",
  "psk": "${PSK}",
  "server_ip": "${PUB_IP}",
  "secret_key": "$(rand_str 32)"
}
CONFEOF
chmod 600 "${PANEL_DIR}/config.json"
PART1

# ==================== PART 2: embed live panel files ====================
emit() {  # emit <src-rel> <dest> <terminator> <chmod>
  {
    echo ""
    echo "cat > \"$2\" <<'$3'"
    cat "${PANEL_DIR}/$1"
    printf '\n'
    echo "$3"
    [ -n "${4:-}" ] && echo "chmod $4 \"$2\""
  } >> "$OUT"
}

echo "  + panel.py"          && emit panel.py              '${PANEL_DIR}/panel.py'          ZQ9PANEL 755
echo "  + sync_users.py"     && emit sync_users.py         '${PANEL_DIR}/sync_users.py'     ZQ9SYNC 755
echo "  + iface_down.py"     && emit iface_down.py         '${PANEL_DIR}/iface_down.py'     ZQ9IFDOWN 755
echo "  + base.html"         && emit templates/base.html   '${PANEL_DIR}/templates/base.html'   ZQ9BASE
echo "  + login.html"        && emit templates/login.html  '${PANEL_DIR}/templates/login.html'  ZQ9LOGIN
echo "  + index.html"        && emit templates/index.html  '${PANEL_DIR}/templates/index.html'  ZQ9INDEX
echo "  + user.html"         && emit templates/user.html   '${PANEL_DIR}/templates/user.html'   ZQ9USER
echo "  + restarting.html"   && emit templates/restarting.html '${PANEL_DIR}/templates/restarting.html' ZQ9RESTART
echo "  + updating.html"     && emit templates/updating.html   '${PANEL_DIR}/templates/updating.html'   ZQ9UPD

# ==================== PART 3: services, firewall, start ====================
cat >> "$OUT" <<'PART3'

# ----------------------------- Services ------------------------------
info "Creating services..."
cat > /etc/systemd/system/l2tp-panel.service <<PANELEOF
[Unit]
Description=3OUTHBOY PANEL Web UI
After=network.target

[Service]
WorkingDirectory=${PANEL_DIR}
ExecStart=/usr/bin/gunicorn --workers 1 --threads 4 --bind 0.0.0.0:${PANEL_PORT} --timeout 60 panel:app
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
PANELEOF

cat > /etc/systemd/system/l2tp-sync.service <<'SYNCEOF'
[Unit]
Description=3OUTHBOY PANEL - user sync and expiry enforcement

[Service]
Type=oneshot
ExecStart=/usr/bin/python3 /opt/l2tp-panel/sync_users.py
SYNCEOF

cat > /etc/systemd/system/l2tp-sync.timer <<'TIMEREOF'
[Unit]
Description=Run L2TP sync every 30 seconds

[Timer]
OnBootSec=30
OnUnitActiveSec=30
AccuracySec=5
Unit=l2tp-sync.service

[Install]
WantedBy=timers.target
TIMEREOF

# ----------------------------- Firewall ------------------------------
if [ "${ENABLE_UFW,,}" != "n" ]; then
  info "Configuring UFW..."
  SSH_PORT="22"
  if [ -n "${SSH_CONNECTION:-}" ]; then
    SP="$(awk '{print $4}' <<<"$SSH_CONNECTION")"
    [[ "$SP" =~ ^[0-9]+$ ]] && SSH_PORT="$SP"
  fi
  ufw allow "${SSH_PORT}/tcp" >/dev/null
  ufw allow 500/udp >/dev/null
  ufw allow 4500/udp >/dev/null
  ufw allow 1701/udp >/dev/null
  if [ -n "$ADMIN_IP" ]; then
    ufw allow from "$ADMIN_IP" to any port "$PANEL_PORT" proto tcp >/dev/null
  else
    ufw allow "${PANEL_PORT}/tcp" >/dev/null
  fi
  ufw route allow from "${POOL_NET}" >/dev/null
  ufw route allow from "${XAUTH_NET}" >/dev/null
  ufw --force enable >/dev/null
  ok "Firewall enabled (SSH:${SSH_PORT} | VPN:500/4500/1701 UDP | Panel:${PANEL_PORT})"
fi

# ----------------------------- Start ---------------------------------
info "Starting services..."
systemctl daemon-reload
systemctl enable --now strongswan-starter >/dev/null 2>&1 || true
systemctl restart strongswan-starter
systemctl enable --now xl2tpd >/dev/null 2>&1 || true
systemctl restart xl2tpd
systemctl enable --now l2tp-nat >/dev/null 2>&1 || true
systemctl restart l2tp-nat
systemctl enable --now l2tp-panel >/dev/null 2>&1 || true
systemctl enable --now l2tp-sync.timer >/dev/null 2>&1 || true
python3 "${PANEL_DIR}/sync_users.py"
ok "All services started."

echo
echo -e "${GREEN}=====================================================${NC}"
echo -e "${GREEN}      3OUTHBOY PANEL — Installation complete!        ${NC}"
echo -e "${GREEN}=====================================================${NC}"
echo -e " Panel URL       : ${CYAN}http://${PUB_IP}:${PANEL_PORT}${NC}"
echo -e " Admin username  : ${CYAN}${ADMIN_USER}${NC}"
echo -e " Admin password  : ${CYAN}${ADMIN_PASS}${NC}"
echo -e " IPSec PSK       : ${CYAN}${PSK}${NC}"
echo -e " Client setup    : L2TP/IPSec PSK | Server: ${PUB_IP}"
echo -e " User status     : http://${PUB_IP}:${PANEL_PORT}/u/<USER_KEY>"
echo
warn "Save these credentials! (also stored in ${PANEL_DIR}/config.json)"
warn "Open UDP 500/4500/1701 and TCP ${PANEL_PORT} in your provider's firewall if any."
PART3

# ----------------------------- verify -----------------------------
bash -n "$OUT" && echo "[OK] Syntax check passed."
LINES=$(wc -l < "$OUT")
echo "[OK] Generated ${OUT} (${LINES} lines)"
echo
echo "Next steps:"
echo "  1) cat /root/install.sh   → copy everything"
echo "  2) GitHub → Panel-L2TP → install.sh → ✏️ Edit → paste → Commit"
echo "  3) Test:  bash <(curl -Ls https://raw.githubusercontent.com/3OUTHBOY/Panel-L2TP/main/install.sh)"
